my coding style

diff --git a/check_git_status b/check_git_status
--- a/check_git_status
+++ b/check_git_status
@@ -1,4 +1,5 @@
-#!/bin/sh
+#! /usr/bin/env sh
+
 # Copyright © 2010 by Daniel Friesel <derf@chaosdorf.de>
 # License: WTFPL:
 #   0. You just DO WHAT THE FUCK YOU WANT TO.
@@ -16,33 +17,29 @@ GIT="/usr/bin/git"
 
 REPO="${1}"
 
-if [ ! -x ${GIT} ]
-then
-	echo "Can't execute ${GIT}"
-	exit $STATE_UNKNOWN
+if [ ! -x ${GIT} ]; then
+  echo "Can't execute ${GIT}"
+  exit $STATE_UNKNOWN
 fi
 
-if [ $# -lt 1 ]
-then
-	echo "Usage: $0 <repo>" 
-	exit $STATE_UNKNOWN
+if [ $# -lt 1 ]; then
+  echo "Usage: $0 <repo>"
+  exit $STATE_UNKNOWN
 fi
 
-if [ -z "${REPO}/.git" -o ! -d "${REPO}/.git" ]
-then
-	echo "No repo specified or ${REPO} is not a git repo";
-	exit $STATE_UNKNOWN
+if [ -z "${REPO}/.git" -o ! -d "${REPO}/.git" ]; then
+  echo "No repo specified or ${REPO} is not a git repo"
+  exit $STATE_UNKNOWN
 fi
 
 cd "${REPO}" || exit $STATE_UNKNOWN
 
-if [ -z "$(${GIT} ls-files --modified --deleted --others --exclude-standard)" ]
-then
-	echo "No uncommited changes in ${REPO}"
-	exit $STATE_OK
+if [ -z "$(${GIT} ls-files --modified --deleted --others --exclude-standard)" ]; then
+  echo "No uncommited changes in ${REPO}"
+  exit $STATE_OK
 else
-	echo "Uncommited changes in ${REPO}"
-	exit $STATE_WARNING
+  echo "Uncommited changes in ${REPO}"
+  exit $STATE_WARNING
 fi
 
 echo "Someting went wrong"
