variable for exitcode

diff --git a/check_freshness_nodejs b/check_freshness_nodejs
--- a/check_freshness_nodejs
+++ b/check_freshness_nodejs
@@ -5,6 +5,8 @@ declare -i STATE_WARNING=1
 declare -i STATE_CRITICAL=2
 declare -i STATE_UNKNOWN=3
 
+declare -i ERR_CODE=$STATE_OK
+
 NODEJS_HOMEPAGE="http://nodejs.org/download/"
 NODEJS_BIN="node"
 
@@ -27,9 +29,9 @@ else
 fi
 
 if [ -n "$ERR_MSG" ]; then
-  echo -e "ERROR: $ERR_MSG"
-  exit $ERR_CODE
+  echo "ERROR: $ERR_MSG"
 else
   echo "OK: Local node.js is up to date"
-  exit $STATE_OK
 fi
+
+exit $ERR_CODE
diff --git a/check_freshness_roundcube b/check_freshness_roundcube
--- a/check_freshness_roundcube
+++ b/check_freshness_roundcube
@@ -5,6 +5,8 @@ declare -i STATE_WARNING=1
 declare -i STATE_CRITICAL=2
 declare -i STATE_UNKNOWN=3
 
+declare -i ERR_CODE=$STATE_OK
+
 SEARCH_DIR="$1"
 
 if [ -z "$SEARCH_DIR" ]; then
@@ -32,9 +34,9 @@ else
 fi
 
 if [ -n "$ERR_MSG" ]; then
-  echo -e "ERROR: $ERR_MSG" | sed 's/, $//g'
-  exit $ERR_CODE
+  echo "ERROR: $ERR_MSG" | sed 's/, $//g'
 else
   echo "OK: all local roundcube webmailer are up to date"
-  exit $STATE_OK
 fi
+
+exit $ERR_CODE
